config/routes.rb
BootstrapStarter::Application.routes.draw do

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}

		namespace :admin do
			resources :users
      resources :soldiers
		end


		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  require 'utf8_converter'

  BOM = "\uFEFF" #Byte Order Mark

  def index
    @soldiers = Soldier.sorted
    

    respond_to do |format|
      format.html { 
        @total_dead = @soldiers.length
        @last_update = Soldier.last_update
        load_chart_gon
        load_map_gon
        gon.app_name = I18n.t('app.common.app_name')
        gon.root_url = root_url
        gon.abbrv_month_names = I18n.t("date.abbr_month_names")
        gon.highcharts_popup_text = I18n.t('highcharts.popup_text')
        gon.shape_text_from = I18n.t('highcharts.shape_text_from')
        gon.shape_text_died = I18n.t('highcharts.shape_text_died')
        render :layout => 'application_root' 
      }
      format.json { render json: @soldiers }
      format.csv { 

        data = CSV.generate() do |csv|
          # column headers
          model_class = Soldier
          model_class_tr = SoldierTranslation
          row = []      
          row << I18n.t('activerecord.attributes.soldier_translation.first_name')
          row << I18n.t('activerecord.attributes.soldier_translation.last_name')
          row << I18n.t('activerecord.attributes.soldier.gender')
          row << I18n.t('activerecord.attributes.soldier.born_at')
          row << I18n.t('activerecord.attributes.soldier_translation.from')
          row << I18n.t('activerecord.attributes.soldier_translation.region_from')
          row << I18n.t('activerecord.attributes.soldier_translation.rank')
          row << I18n.t('activerecord.attributes.soldier_translation.served_with')
          row << I18n.t('activerecord.attributes.soldier_translation.country_died')
          row << I18n.t('activerecord.attributes.soldier_translation.place_died')
          row << I18n.t('activerecord.attributes.soldier_translation.incident_type')
          row << I18n.t('activerecord.attributes.soldier_translation.incident_description')
          row << I18n.t('activerecord.attributes.soldier.died_at')
          row << I18n.t('activerecord.attributes.soldier.age')
          csv << row

          @soldiers.each do |soldier|
            row = []
            row << soldier.first_name
            row << soldier.last_name
            row << soldier.gender
            row << soldier.born_at
            row << soldier.place_from
            row << soldier.region_from
            row << soldier.rank
            row << soldier.served_with
            row << soldier.country_died
            row << soldier.place_died
            row << soldier.incident_type
            row << soldier.incident_description
            row << soldier.died_at
            row << soldier.age
            csv << row
          end
        end

        filename = Utf8Converter.generate_permalink(I18n.t('app.common.app_name') + "_" + Time.now.strftime('%F_%R'))
        send_data BOM + data,
         :type => 'text/csv; charset=iso-8859-1; header=present',
         :disposition => "attachment; filename=#{filename}.csv" 
      }
    end

  end



protected

  def load_chart_gon
    # text for print and export buttons in highcharts
    gon.highcharts_downloadPNG = t('highcharts.downloadPNG')
    gon.highcharts_downloadJPEG = t('highcharts.downloadJPEG')
    gon.highcharts_downloadPDF = t('highcharts.downloadPDF')
    gon.highcharts_downloadSVG = t('highcharts.downloadSVG')
    gon.highcharts_printChart = t('highcharts.printChart')

    # gender
    gon.gender_title = I18n.t('summary.titles.gender')
    x = Soldier.summary_gender
    if x.present?
      gon.gender_headers = x["headers"]
      gon.gender_values = x["values"]
    end

    # age
    gon.age_title = I18n.t('summary.titles.age')
    x = Soldier.summary_age
    if x.present?
      gon.age_headers = x["headers"]
      gon.age_values = x["values"]
    end

    # country
    gon.country_title = I18n.t('summary.titles.country')
    x = Soldier.summary_country_died
    if x.present?
      gon.country_headers = x["headers"]
      gon.country_values = x["values"]
    end
  
    # date died
    gon.date_died_title = I18n.t('summary.titles.date_died')
    x = Soldier.summary_date_died
    if x.present?
      gon.date_died_headers = x["headers"]
      gon.date_died_values = x["values"]
    end

    # date died filtered
    x = Soldier.summary_date_died_filtered
    if x.present?
      gon.date_died_filtered = x
    end

    # rank
    gon.rank_title = I18n.t('summary.titles.rank')
    x = Soldier.summary_rank
    if x.present?
      gon.rank_headers = x["headers"]
      gon.rank_values = x["values"]
    end

    # served with
    gon.served_with_title = I18n.t('summary.titles.served_with')
    x = Soldier.summary_served_with
    if x.present?
      gon.served_with_headers = x["headers"]
      gon.served_with_values = x["values"]
    end

    # incident description
    gon.incident_description_title = I18n.t('summary.titles.incident_description')
    x = Soldier.summary_incident_description
    if x.present?
      gon.incident_description_headers = x["headers"]
      gon.incident_description_values = x["values"]
    end
=begin
    # incidents
    x = Soldier.summary_incidents_grouped
    if x.present?
      @num_incidents = x.length
      gon.incidents_num = x.length
      gon.incident_types = []
      for i in 0..x.length-1
        h = Hash.new
        gon.incident_types << h
        h[:title] = x[i]["header"]
        h[:headers] = x[i]["items"]["headers"]
        h[:values] = x[i]["items"]["values"]
      end
    end
=end
  end

  def load_map_gon
    region_from = Soldier.summary_region_from
    place_died = Soldier.summary_place_died

    # georgia
#    json = JSON.parse(File.open("#{Rails.root}/public/georgia_regions_#{I18n.locale}.json", "r") {|f| f.read()})
    json = JSON.parse(File.open("#{Rails.root}/public/georgia.json", "r") {|f| f.read()})
    add_data_to_json(json, region_from)
#    gon.map_georgia = json
    gon.map_georgia = true
    File.open("#{Rails.root}/public/georgia_with_data.json", 'w') {|f| f.write(json.to_json) }

    # afghan
    json = JSON.parse(File.open("#{Rails.root}/public/afghan.json", "r") {|f| f.read()})
    add_data_to_json(json, place_died)
#    gon.map_afghan = json
    gon.map_afghan = true
    File.open("#{Rails.root}/public/afghan_with_data.json", 'w') {|f| f.write(json.to_json) }

    # iraq
    json = JSON.parse(File.open("#{Rails.root}/public/iraq.json", "r") {|f| f.read()})
    add_data_to_json(json, place_died)
#    gon.map_iraq = json
    gon.map_iraq = true
    File.open("#{Rails.root}/public/iraq_with_data.json", 'w') {|f| f.write(json.to_json) }
  
  end

  def add_data_to_json(json, data)
    if json && data && !data.empty?
      json['features'].each do |value|
        index = data["headers"].index{|x| x == value['properties']['Shape_Name_' + I18n.locale.to_s]}
        if index.present?
          value['properties']['count'] = data["values"][index]
          value['properties']['classname'] = data["css_classes"][index]
        else
          value['properties']['count'] = 0
          value['properties']['classname'] = "map_color0"
        end
      end
    end
  end

end

app/views/root/index.html.erb
<%- model_class = Soldier -%>
<%- model_class_tr = SoldierTranslation -%>

<div id="thumbs" class="clear">
  <ul>
    <% @soldiers.each do |soldier| %>
      <li>
        <a href="javascript:;" data-id="<%= soldier.id %>" data-name="<%= soldier.full_name %>"
      data-age="<%= soldier.age%>" data-gender="<%= soldier.gender %>" data-rank="<%= soldier.rank %>" 
      data-incident-type="<%= soldier.incident_type %>" data-incident-description="<%= soldier.incident_description %>"
      data-country="<%= soldier.country_died %>" data-date-died="<%= soldier.died_at.beginning_of_month %>" 
      data-served-with="<%= soldier.served_with%>" data-permalink="<%=soldier.permalink%>"
      data-region-from="<%= soldier.region_from%>" data-place-died="<%=soldier.place_died%>" 
      title="<%= soldier.full_name %> <%= t('.photo_text') %>" >
          <%= image_tag soldier.img_bw.url, :alt => soldier.full_name %>
          <%= image_tag soldier.img.url, :alt => soldier.full_name %>
        </a>
      </li>
    <% end %>
  </ul>
</div>


<div id="soldier_profiles">
<% @soldiers.each do |soldier| %>
  <div id="soldier_profile_<%=soldier.id%>" class="soldier_profile row-fluid" data-id="<%= soldier.id %>">
    <!--<div class="soldier_photo span1"></div>-->
    <div class="soldier_photo span3">
      <%= image_tag soldier.img.url, :alt => soldier.full_name %>
    </div>
    <div class="soldier_bio span8">
      <h2>
        <%= soldier.full_name %>
        <div class="social_profile">
          <img src="/assets/share_shr.png" />
          <div class="social_profile_hover">
            <div class="addthis_toolbox addthis_default_style ">
              <a class="addthis_counter addthis_pill_style" addthis:title='<%= "#{soldier.full_name} | #{I18n.t("app.common.app_name")}" %>'></a>
            </div>
          </div>
        </div>
      </h2>
      <div class="row-fluid">
        <div class="span6">
          <ul>
            <li>
              <strong><%= model_class.human_attribute_name(:age) %>:</strong>
              <%= soldier.age %>
            </li>
            <li>
              <strong><%= model_class.human_attribute_name(:gender) %>:</strong>
              <%= soldier.gender %>
            </li>
            <li>
              <strong><%= t('.hometown') %>:</strong>
              <%= soldier.place_from.present? ? "#{soldier.place_from}, #{soldier.region_from}" : nil %>
            </li>
            <li>
              <strong><%= model_class_tr.human_attribute_name(:rank) %>:</strong>
              <%= soldier.rank %>
            </li>
            <li>
              <strong><%= model_class_tr.human_attribute_name(:served_with) %>:</strong>
              <%= soldier.served_with %>
            </li>
          </ul>
        </div>
        <div class="soldier_incident span4">
          <ul>
            <li>
              <strong><%= t('.incident') %>:</strong>
              <%= soldier.incident_type %>
              -
              <%= soldier.incident_description %>
            </li>
            <li>
              <strong><%= t('.location') %>:</strong>  
              <%= soldier.place_died.present? ? "#{soldier.place_died}, #{soldier.country_died}" : soldier.country_died %>
            </li>
            <li>
              <strong><%= t('.date') %>:</strong>  
              <%= l soldier.died_at, :format => :long if soldier.died_at.present? %>
            </li>
            <% if user_signed_in? && current_user.role?(User::ROLES[:user]) %>
              <li>
                <%= link_to t('helpers.links.edit'), edit_admin_soldier_path(soldier.id), :class => 'btn btn-mini' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="soldier_nav span1">
      <ul>
        <li class="soldier_nav_close">
          <a href="javascript:;">
            <%= image_tag "x.jpg", :alt => 'close', :title => 'close' %>
            <%= image_tag "x_hover.jpg", :alt => 'close', :title => 'close' %>
          </a>
        </li>
        <li class="soldier_nav_next">
          <a href="javascript:;" data-id="<%= soldier.id %>">
            <%= image_tag ">.jpg", :alt => t('helpers.links.next'), :title => t('helpers.links.next') %>
            <%= image_tag ">_hover.jpg", :alt => t('helpers.links.next'), :title => t('helpers.links.next') %>
          </a>
        </li>
        <li class="soldier_nav_previous">
          <a href="javascript:;" data-id="<%= soldier.id %>">
            <%= image_tag "<.jpg", :alt => t('helpers.links.previous'), :title => t('helpers.links.previous') %>
            <%= image_tag "<_hover.jpg", :alt => t('helpers.links.previous'), :title => t('helpers.links.previous') %>
          </a>
        </li>
      </ul>
    </div>
  </div>
<% end %>
</div>


<div id="maps">
  <div id="map_container">
    <div id="map_georgia_container">
      <h3><%= t('.map_georgia_header') %></h3>
      <div id="map_georgia"></div>
    </div>
    <div id="map_afghan_container">
      <h3><%= t('.map_afghan_header') %></h3>
      <div id="map_afghan"></div>
    </div>
    <div id="map_iraq_container">
      <h3><%= t('.map_iraq_header') %></h3>
      <div id="map_iraq"></div>
    </div>
  </div>
  <div id="map_legend">
    <div>
      <span class="map_color0"></span>
      0
    </div>
    <div>
      <span class="map_color1"></span>
      1
    </div>
    <div>
      <span class="map_color2"></span>
      2
    </div>
    <div>
      <span class="map_color3"></span>
      3-6
    </div>
    <div>
      <span class="map_color4"></span>
      7-10
    </div>
    <div>
      <span class="map_color5"></span>
      > 10
    </div>
  </div>
</div>

<div id="charts">
  <div id="chart_gender"></div>
  <div id="chart_age"></div>
  <div id="chart_country"></div>
  <div id="chart_incident_description"></div>

  <%
=begin
   if @num_incidents > 0 %>
    <% for i in 0..@num_incidents-1 %>
      <div id="chart_incident_type_<%= i %>"></div>
    <% end %>
  <% end %>
<%
=end %>
  <div id="chart_rank"></div>
  <div id="chart_served_with"></div>
  <div id="chart_date_died"></div>
</div>  