config/routes.rb
BootstrapStarter::Application.routes.draw do

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}

		namespace :admin do
			resources :users
      resources :soldiers
		end


		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
	# :registerable, :recoverable,
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role

  validates :role, :presence => true

  def self.no_admins
    where("role != ?", ROLES[:admin])
  end

	# if no role is supplied, default to the basic user role
	def check_for_role
		self.role = ROLES[:user] if self.role.nil?
	end

  # use role inheritence
  # - a role with a larger number can do everything that smaller numbers can do
  ROLES = {:user => 0, :admin => 99}
  def role?(base_role)
    if base_role && ROLES.values.index(base_role)
      return base_role <= self.role
    end
    return false
  end
  
  def role_name
    ROLES.keys[ROLES.values.index(self.role)].to_s
  end
  
  def nickname
    self.email.split('@')[0]
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter do |controller_instance|
    controller_instance.send(:valid_role?, User::ROLES[:admin])
  end

  # GET /admin/users
  # GET /admin/users.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: UsersDatatable.new(view_context, current_user) }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @user = User.find(params[:id])
    if @user.role == User::ROLES[:admin] && current_user.role != User::ROLES[:admin]
      redirect_to admin_users_path
    end
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: t('app.msgs.success_created', :obj => t('activerecord.models.user')) }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      success = if params[:user][:password].present? || params[:user][:password_confirmation].present?
        @user.update_attributes(params[:user])
      else
        @user.update_without_password(params[:user])
      end

      if success
        format.html { redirect_to admin_users_path, notice: t('app.msgs.success_updated', :obj => t('activerecord.models.user')) }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end
end

app/views/admin/users/_form.html.erb
<%= semantic_form_for([:admin,@user]) do |f| %>
	<%= f.error_messages %>

	<%= f.inputs do %>
		<%= f.input :email, :input_html => {:size =>35} %>
		<%= f.input :password, :input_html => {:size => 35}  %>
		<%= f.input :password_confirmation, :input_html => {:size => 35}  %>
		<% if current_user.role?(User::ROLES[:admin]) %>
			<%= f.input :role, :as => :select, :collection => User::ROLES.map{|key,value| [key.to_s.humanize, value.to_s]}  %>
		<% else %>
			<%= f.hidden_field :role , :value => User::ROLES[:user] %>
		<% end %>

	<% end %>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
	  <%= f.submit nil, :class => 'btn btn-warning', :type => :reset, :value => t('helpers.links.reset'), :name => :reset %>
	  <%= link_to t('helpers.links.cancel'), admin_users_path, :class => 'btn btn-mini btn-warning' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%- model_class = User -%>
<% title t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %>

<div class="form-actions">
	<%= link_to t('helpers.links.list'), admin_users_path,
  :class => 'btn' %>
	<%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/users/index.html.erb
<%- model_class = User -%>
<% title t '.title', :default => model_class.model_name.human.pluralize %>

<div class="form-actions">
<%= link_to t('helpers.links.new'),
            new_admin_user_path,
            :class => 'btn btn-primary' %>
<%= link_to t('helpers.links.admin'), admin_path,
:class => 'btn' %>
</div>

<table class="table table-striped display" id="users-datatable" data-source="<%= admin_users_url(:format => :json) %>">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:role) %></th>
      <th><%=	t('app.common.actions') %></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<%- model_class = User -%>
<% title t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %>

<%= render :partial => 'form' %>

<div class="form-actions">
	<%= link_to t('helpers.links.list'), admin_users_path,
  :class => 'btn' %>
	<%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn' %>
</div>

app/views/admin/users/show.html.erb
<%- model_class = User -%>
<% title t '.title', :default => model_class.model_name.human %>

<div class="form-actions">
  <%= link_to t('helpers.links.list'),
              admin_users_path, :class => 'btn'  %>
  <%= link_to t('helpers.links.edit'),
              edit_admin_user_path(@user), :class => 'btn' %>
  <%= link_to t('helpers.links.delete'),
              admin_user_path(@user),
              :method => :delete,
							:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm")) },
              :class => 'btn btn-danger' %>
	<%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn' %>
</div>

<p>
  <strong><%= model_class.human_attribute_name(:email) %>:</strong>
  <%= @user.email %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:role) %>:</strong>
  <%= @user.role_name.humanize %>
</p>