config/routes.rb
BootstrapStarter::Application.routes.draw do

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}

		namespace :admin do
			resources :users
      resources :soldiers
		end


		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/models/soldier.rb
# encoding: utf-8
class Soldier < ActiveRecord::Base
	require 'json'
  require 'json_cache'

	translates :permalink, :first_name, :last_name, :place_from, :region_from, :rank, :served_with, :country_died, :place_died, :incident_type, :incident_description, :region_from

	has_attached_file :img, :url => "/system/photo/:id/:permalink.:extension",
                  :default_url => "/assets/missing.jpg"

	has_attached_file :img_bw, :url => "/system/photo/:id/:permalink_bw.:extension",
                  :default_url => "/assets/missing_bw.jpg"

	has_many :soldier_translations, :dependent => :destroy
  accepts_nested_attributes_for :soldier_translations
  attr_accessible :soldier_translations_attributes,
      :born_at,
      :died_at,
      :age, 
      :is_male, 
      :img,
      :img_file_name,
      :img_content_type,
      :img_file_size,
      :img_updated_at,
      :img_bw,
      :img_bw_file_name,
      :img_bw_content_type,
      :img_bw_file_size,
      :img_bw_updated_at

  validates :died_at, :presence => true

  CACHE_KEY_GENDER = "[locale]/gender"
  CACHE_KEY_AGE = "[locale]/age"
  CACHE_KEY_COUNTRY_DIED = "[locale]/country_died"
  CACHE_KEY_PLACE_DIED = "[locale]/place_died"
  CACHE_KEY_RANK = "[locale]/rank"
  CACHE_KEY_SERVED_WITH = "[locale]/served_with"
  CACHE_KEY_INCIDENT_TYPE = "[locale]/incident_type"
  CACHE_KEY_INCIDENT_DESCRIPTION = "[locale]/incident_description"
  CACHE_KEY_INCIDENTS = "[locale]/incidents"
  CACHE_KEY_DATE_DIED = "[locale]/date_died"
  CACHE_KEY_DATE_DIED_FILTERED = "[locale]/date_died_filtered"
  CACHE_KEY_PLACE_FROM = "[locale]/place_from"
  CACHE_KEY_REGION_FROM = "[locale]/region_from"
  CACHE_KEY_LAST_UPDATED = "[locale]/last_updated"

  def self.sorted
    with_translations(I18n.locale).order("soldiers.died_at DESC, soldier_translations.last_name ASC")
  end

  def self.last_update
		h = JsonCache.fetch(CACHE_KEY_LAST_UPDATED.gsub("[locale]", I18n.locale.to_s)) {
      z = []
      x = select('created_at').order('created_at desc').limit(1)
      if x.present?
        z << I18n.l(x.first.created_at, :format => :no_time)
      end
      z.to_json
    }
    return JSON.parse(h).first
  end

  def full_name
    self.first_name.strip() + " " + self.last_name.strip()
  end

  def gender
    if self.is_male 
      I18n.t('summary.male') 
    else 
      I18n.t('summary.female') 
    end 
  end

  # the image uses the permalink value which can be different for each langauge
  # use the ka value as the common permalink
  def common_permalink
    self.soldier_translations.select{|x| x.locale == "ka"}.first.permalink
  end

  ######################
  ## summary queries
  ## all formats are { headers => [], values => []}
  ######################
  # gender
  def self.summary_gender
		h = JsonCache.fetch(CACHE_KEY_GENDER.gsub("[locale]", I18n.locale.to_s)) {
      h = Hash.new
      h[:headers] = []
      h[:values] = []
      x = Soldier.count(:group => :is_male)

      h[:headers] << I18n.t('summary.male')
      h[:values] << (x.has_key?(true).present? ? x[true] : 0)

      h[:headers] << I18n.t('summary.female')
      h[:values] << (x.has_key?(false).present? ? x[false] : 0)
      h.to_json
    }
    return JSON.parse(h)
  end

  # age 
  # groups: 20-24, 25-29, 30-34, 35-39, 40-49
  AGE_CATEGORIES = ["20-24", "25-29", "30-34", "35-39", "40-49"]
  def self.summary_age
		h = JsonCache.fetch(CACHE_KEY_AGE.gsub("[locale]", I18n.locale.to_s)) {
      h = Hash.new
      h[:headers] = []
      h[:values] = []
      h[:min] = []
      h[:max] = []
      x = Soldier.select('age')

      h[:headers] << AGE_CATEGORIES[0]
      ary = x.select{|x| x.age <= 24 && x.age >= 20}
      h[:values] << (ary.present? ? ary.length : 0)
      h[:min] << 20
      h[:max] << 24

      h[:headers] << AGE_CATEGORIES[1]
      ary = x.select{|x| x.age <= 29 && x.age >= 25}
      h[:values] << (ary.present? ? ary.length : 0)
      h[:min] << 25
      h[:max] << 29

      h[:headers] << AGE_CATEGORIES[2]
      ary = x.select{|x| x.age <= 34 && x.age >= 30}
      h[:values] << (ary.present? ? ary.length : 0)
      h[:min] << 30
      h[:max] << 34

      h[:headers] << AGE_CATEGORIES[3]
      ary = x.select{|x| x.age <= 39 && x.age >= 35}
      h[:values] << (ary.present? ? ary.length : 0)
      h[:min] << 35
      h[:max] << 39

      h[:headers] << AGE_CATEGORIES[4]
      ary = x.select{|x| x.age <= 49 && x.age >= 40}
      h[:values] << (ary.present? ? ary.length : 0)
      h[:min] << 40
      h[:max] << 49

      h.to_json
    }
    return JSON.parse(h)
  end

  # date died
  def self.summary_date_died
		h = JsonCache.fetch(CACHE_KEY_DATE_DIED.gsub("[locale]", I18n.locale.to_s)) {
      h = Hash.new
      h[:headers] = []
      h[:values] = []
      x = Soldier.select("died_at").group_by{|x| x.died_at.beginning_of_month}
      start_year = 2004
      end_year = Time.now.year

      if x.present?
        dates = []
        x.keys.each do |key|
          dates << {:month => key.month, :year => key.year, :count => x[key].count}
        end
    
        for i in start_year..end_year
          for j in 1..12
            h[:headers] << "#{i} #{I18n.t("date.abbr_month_names")[j]}"
            date = dates.select{|x| x[:month] == j && x[:year] == i}
            h[:values] << (date.present? ? date.first[:count] : nil)

            # if this is the current month/year, stop
            break if i==end_year && j==Time.now.month
          end
        end
      end
      h.to_json
    }

    return JSON.parse(h)
  end

  # date died filtered
  # just get unique dates that have deaths
  def self.summary_date_died_filtered
		h = JsonCache.fetch(CACHE_KEY_DATE_DIED_FILTERED.gsub("[locale]", I18n.locale.to_s)) {
      Soldier.select("died_at").order("died_at").group_by{|x| x.died_at.beginning_of_month}.map{|x| x[0]}.to_json
    }
    return JSON.parse(h)
  end

  # place from
  def self.summary_place_from
		h = JsonCache.fetch(CACHE_KEY_PLACE_FROM.gsub("[locale]", I18n.locale.to_s)) {
      x = Hash[SoldierTranslation.where(:locale => I18n.locale).count(:group => :place_from).sort_by{|k,v| -v}]
      create_summary_array_with_classes(x).to_json
    }
    return JSON.parse(h)
  end

  # region from
  def self.summary_region_from
		h = JsonCache.fetch(CACHE_KEY_REGION_FROM.gsub("[locale]", I18n.locale.to_s)) {
      x = Hash[SoldierTranslation.where(:locale => I18n.locale).count(:group => :region_from).sort_by{|k,v| -v}]
      create_summary_array_with_classes(x).to_json
    }
    return JSON.parse(h)
  end

  # rank
  RANK_ORDER_EN = ['Colonel', 'Chief Lieutenant ', 'Lieutenant', 'Sergeant', 'Junior Sergeant', 'Corporal', 'Private 1st Class', 'Private']
  RANK_ORDER_KA = ['პოლკოვნიკი', 'უფროსი ლეიტენანტი', 'ლეიტენანტი', 'სერჟანტი', 'უმცროსი სერჟანტი', 'კაპრალი', 'პირველი კლასის რიგითი', 'რიგითი']
  def self.summary_rank
		h = JsonCache.fetch(CACHE_KEY_RANK.gsub("[locale]", I18n.locale.to_s)) {
      x = SoldierTranslation.where(:locale => I18n.locale).count(:group => :rank)
      # build a new hash in the correct rank order
      r = Hash.new
      ary = I18n.locale == :en ? RANK_ORDER_EN : RANK_ORDER_KA
      ary.each do |a|
        count = x.select{|k,v| k == a}.map{|k,v| v}

        r[a] = count.present? ? count.first : 0
      end

      create_summary_array(r).to_json
    }
    return JSON.parse(h)
  end

  # served with
  def self.summary_served_with
		h = JsonCache.fetch(CACHE_KEY_SERVED_WITH.gsub("[locale]", I18n.locale.to_s)) {
      x = Hash[SoldierTranslation.where(:locale => I18n.locale).count(:group => :served_with).sort_by{|k,v| -v}]
      create_summary_array(x).to_json
    }
    return JSON.parse(h)
  end

  # country died
  def self.summary_country_died
		h = JsonCache.fetch(CACHE_KEY_COUNTRY_DIED.gsub("[locale]", I18n.locale.to_s)) {
      x = Hash[SoldierTranslation.where(:locale => I18n.locale).count(:group => :country_died).sort_by{|k,v| -v}]
      create_summary_array(x).to_json
    }
    return JSON.parse(h)
  end

  # place died
  def self.summary_place_died
		h = JsonCache.fetch(CACHE_KEY_PLACE_DIED.gsub("[locale]", I18n.locale.to_s)) {
      x = Hash[SoldierTranslation.where(:locale => I18n.locale).count(:group => :place_died).sort_by{|k,v| -v}]
      create_summary_array_with_classes(x).to_json
    }
    return JSON.parse(h)
  end

  # incident type
  def self.summary_incident_type
		h = JsonCache.fetch(CACHE_KEY_INCIDENT_TYPE.gsub("[locale]", I18n.locale.to_s)) {
      x = Hash[SoldierTranslation.where(:locale => I18n.locale).count(:group => :incident_type).sort_by{|k,v| -v}]
      create_summary_array(x).to_json
    }
    return JSON.parse(h)
  end

  # incident desc
  def self.summary_incident_description
		h = JsonCache.fetch(CACHE_KEY_INCIDENT_DESCRIPTION.gsub("[locale]", I18n.locale.to_s)) {
      x = Hash[SoldierTranslation.where(:locale => I18n.locale).count(:group => :incident_description).sort_by{|k,v| -v}]
      create_summary_array(x).to_json
    }
    return JSON.parse(h)
  end

  # for each incident type, get summary of incident descriptions
  # format: [{header value items => {headers values}}, {header value items => {headers values}}, etc]
  def self.summary_incidents_grouped
		h = JsonCache.fetch(CACHE_KEY_INCIDENTS.gsub("[locale]", I18n.locale.to_s)) {
      h = []
      x = summary_incident_type

      if x.present?
        for i in 0..x["headers"].length-1
          z = Hash.new
          h << z
          z[:header] = x["headers"][i]
          z[:value] = x["values"][i]
          a = Hash[SoldierTranslation.where(:locale => I18n.locale, :incident_type => z[:header]).count(:group => :incident_description).sort_by{|k,v| -v}]
          z[:items] = create_summary_array(a)
        end
      end
      h.to_json
    }

    return JSON.parse(h)
  end

  ######################
  ## load from json
  ## - expect each item to have key names that match attr names
  ######################
  def self.load_from_json(en_json, ka_json, color_image_path=nil, bw_image_path=nil)

app/controllers/admin/soldiers_controller.rb
class Admin::SoldiersController < ApplicationController
  require 'json_cache'

  before_filter :authenticate_user!
  before_filter do |controller_instance|
    controller_instance.send(:valid_role?, User::ROLES[:user])
  end

  # GET /soldiers
  # GET /soldiers.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: SoldiersDatatable.new(view_context) }
    end
  end

  # GET /soldiers/1
  # GET /soldiers/1.json
  def show
    @soldier = Soldier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @soldier }
    end
  end

  # GET /soldiers/new
  # GET /soldiers/new.json
  def new
    @soldier = Soldier.new

    # create the translation object for the locales that were selected
	  # so the form will properly create all of the nested form fields
		I18n.available_locales.each do |locale|
			@soldier.soldier_translations.build(:locale => locale.to_s)
		end

    gon.edit_soldier = true

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @soldier }
    end
  end

  # GET /soldiers/1/edit
  def edit
    @soldier = Soldier.find(params[:id])
    gon.edit_soldier = true
#		gon.born_at = @soldier.born_at.strftime('%m/%d/%Y') if @soldier.born_at.present?
		gon.died_at = @soldier.died_at.strftime('%m/%d/%Y') if @soldier.died_at.present?
  end

  # POST /soldiers
  # POST /soldiers.json
  def create
    @soldier = Soldier.new(params[:soldier])

    respond_to do |format|
      if @soldier.save
        # clear the cache files so the new data is avaialble
        JsonCache.clear

        format.html { redirect_to admin_soldier_path(@soldier), notice: t('app.msgs.success_created', :obj => t('activerecord.models.soldier')) }
        format.json { render json: @soldier, status: :created, location: @soldier }
      else
        gon.edit_soldier = true
#		    gon.born_at = @soldier.born_at.strftime('%m/%d/%Y') if @soldier.born_at.present?
		    gon.died_at = @soldier.died_at.strftime('%m/%d/%Y') if @soldier.died_at.present?
        format.html { render action: "new" }
        format.json { render json: @soldier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /soldiers/1
  # PUT /soldiers/1.json
  def update
    @soldier = Soldier.find(params[:id])

    respond_to do |format|
      if @soldier.update_attributes(params[:soldier])
        # clear the cache files so the new data is avaialble
        JsonCache.clear

        format.html { redirect_to admin_soldier_path(@soldier), notice: t('app.msgs.success_created', :obj => t('activerecord.models.soldier')) }
        format.json { head :ok }
      else
        gon.edit_soldier = true
#		    gon.born_at = @soldier.born_at.strftime('%m/%d/%Y') if @soldier.born_at.present?
		    gon.died_at = @soldier.died_at.strftime('%m/%d/%Y') if @soldier.died_at.present?
        format.html { render action: "edit" }
        format.json { render json: @soldier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /soldiers/1
  # DELETE /soldiers/1.json
  def destroy
    @soldier = Soldier.find(params[:id])
    @soldier.destroy

    respond_to do |format|
      format.html { redirect_to adminsoldiers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/soldiers_helper.rb
module SoldiersHelper
end

app/views/admin/soldiers/_form.html.erb
<%= semantic_form_for([:admin,@soldier], :html => { :class => 'form-horizontal' }) do |f| %>
	<%= f.error_messages %>

  <% @soldier.soldier_translations.sort{|x,y| x.locale <=> y.locale}.each do |trans| %>
	  <%= f.fields_for :soldier_translations, trans do |translation| %>

		  <div id="form-<%= trans.locale %>" class="multilanguage">
			  <h3><%= t("app.language.#{trans.locale}") %></h3>
			  <%= translation.input :first_name %>
			  <%= translation.input :last_name %>
			  <%= translation.input :place_from %>
			  <%= translation.input :rank %>
			  <%= translation.input :served_with %>
			  <%= translation.input :country_died %>
			  <%= translation.input :place_died %>
			  <%= translation.input :incident_type %>
			  <%= translation.input :incident_description %>
			  <%= translation.hidden_field :locale , :value => trans.locale %>
		  </div>

	  <% end %>
  <% end %>

	<%= f.input :born_at, :as => :string, :input_html => {:size => 35} %>
	<%= f.input :died_at, :as => :string, :input_html => {:size => 35} %>
	<%= f.input :age, :as => :string, :input_html => {:size => 3} %>
	<%= f.input :is_male, :as => :radio %>
  <%= f.input :img, :as => :file %>
  <% if @soldier.img_file_name.present? %>
    <div class="control-group">
      <div class="controls">
        <%= image_tag @soldier.img.url %>
      </div>
    </div>
  <% end %>
  <%= f.input :img_bw, :as => :file %>
  <% if @soldier.img_bw_file_name.present? %>
    <div class="control-group">
      <div class="controls">
        <%= image_tag @soldier.img_bw.url %>
      </div>
    </div>
  <% end %>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
	  <%= f.submit nil, :class => 'btn btn-warning', :type => :reset, :value => t('helpers.links.reset'), :name => :reset %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_soldiers_path, :class => 'btn btn-mini btn-warning' %>
  </div>

<% end %>

app/views/admin/soldiers/edit.html.erb
<%- model_class = Soldier -%>
<% title t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %>

<div class="form-actions">
	<%= link_to t('helpers.links.list'), admin_soldiers_path,
  :class => 'btn' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/soldiers/index.html.erb
<%- model_class = Soldier -%>
<%- model_class_tr = SoldierTranslation -%>
<% title t '.title', :default => model_class.model_name.human.pluralize %>

<div class="form-actions">
  <%= link_to t('helpers.links.new'),
              new_admin_soldier_path,
              :class => 'btn btn-primary' %>
</div>

<table class="table table-striped display" id="soldiers-datatable" data-source="<%= admin_soldiers_url(:format => :json) %>">
  <thead>
    <tr>
      <th></th>
      <th><%= model_class_tr.human_attribute_name(:name) %></th>
      <th><%= model_class_tr.human_attribute_name(:rank) %></th>
      <th><%= model_class_tr.human_attribute_name(:served_with) %></th>
      <th><%= model_class_tr.human_attribute_name(:country_died) %></th>
      <th><%= model_class_tr.human_attribute_name(:place_died) %></th>
      <th><%= model_class_tr.human_attribute_name(:incident_type) %></th>
      <th><%= model_class_tr.human_attribute_name(:incident_description) %></th>
      <th><%= model_class.human_attribute_name(:died_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
</table>

app/views/admin/soldiers/new.html.erb
<%- model_class = Soldier -%>
<% title t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %>

<div class="form-actions">
	<%= link_to t('helpers.links.list'), admin_soldiers_path,
  :class => 'btn' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/soldiers/show.html.erb
<%- model_class = Soldier -%>
<%- model_class_tr = SoldierTranslation -%>
<% title t '.title', :default => model_class.model_name.human %>

<div class="form-actions">
  <%= link_to t('helpers.links.list'),
              admin_soldiers_path, :class => 'btn'  %>
  <%= link_to t('helpers.links.edit'),
              edit_admin_soldier_path(@soldier), :class => 'btn' %>
  <%= link_to t('helpers.links.delete'),
              admin_soldier_path(@soldier),
              :method => :delete,
							:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm")) },
              :class => 'btn btn-danger' %>
</div>

  <p>
    <%= image_tag @soldier.img.url %>
    <%= image_tag @soldier.img_bw.url %>
  </p>
  <p><strong><%= model_class_tr.human_attribute_name(:first_name) %>:</strong>
  <%= @soldier.first_name %></p>
  <p><strong><%= model_class_tr.human_attribute_name(:last_name) %>:</strong>
  <%= @soldier.last_name %></p>
  <p><strong><%= model_class_tr.human_attribute_name(:from) %>:</strong>
  <%= @soldier.place_from %></p>
  <p><strong><%= model_class.human_attribute_name(:born_at) %>:</strong>
  <%= @soldier.born_at %></p>
  <p><strong><%= model_class_tr.human_attribute_name(:rank) %>:</strong>
  <%= @soldier.rank %></p>
  <p><strong><%= model_class_tr.human_attribute_name(:served_with) %>:</strong>
  <%= @soldier.served_with %></p>
  <p><strong><%= model_class_tr.human_attribute_name(:country_died) %>:</strong>
  <%= @soldier.country_died %></p>
  <p><strong><%= model_class_tr.human_attribute_name(:place_died) %>:</strong>
  <%= @soldier.place_died %></p>
  <p><strong><%= model_class_tr.human_attribute_name(:incident_type) %>:</strong>
  <%= @soldier.incident_type %></p>
  <p><strong><%= model_class_tr.human_attribute_name(:incident_description) %>:</strong>
  <%= @soldier.incident_description %></p>
  <p><strong><%= model_class.human_attribute_name(:died_at) %>:</strong>
  <%= @soldier.died_at %></p>
  <p><strong><%= model_class.human_attribute_name(:age) %>:</strong>
  <%= @soldier.age %></p>
  <p><strong><%= model_class.human_attribute_name(:is_male) %>:</strong>
  <%= @soldier.is_male %></p>