config/routes.rb
BootstrapStarter::Application.routes.draw do

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}

		namespace :admin do
			resources :users
      resources :soldiers
		end


		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? "#{yield(:title)} | #{t('app.common.app_name')}" :
				t('app.common.app_name') %></title>
    <%= csrf_meta_tags %>
	  <%= include_gon %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
		<!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
	  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to(t('app.common.app_name'), root_path(:locale => I18n.locale),:class=>"brand font")%>
          <div class="container-fluid nav-collapse">

	          <ul class="nav pull-right">
		          <% if user_signed_in? %>
				        <li class="dropdown">
				          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
				                <%= current_user.nickname %>
				                <b class="caret"></b>
				          </a>
				          <ul class="dropdown-menu">
               			<li>
                     <%= link_to t('.soldiers'), admin_soldiers_path %>
                    </li>
                    <% if current_user.role? User::ROLES[:admin] %>
                 			<li>
                       <%= link_to t('.users'), admin_users_path %>
                      </li>
                    <% end %> 		
						        <li>
				 		         <%= link_to t('.sign_out'), destroy_user_session_path, :method => :delete %>
										</li>
				          </ul>
				        </li>
		          <% end %>
							<% I18n.available_locales.each do |locale| %>
								<% if locale != I18n.locale %>
									<li><%= link_to t("app.language.#{locale}"), params.merge(:locale => locale) %></li>
								<% end %>
							<% end %>
	          </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

		<div id="wrapper">
		  <div class="container-fluid">
		    <div class="content">
		      <div class="row-fluid">
		         <div class="span12">
							<% flash.each do |key, msg| %>
								<div class="alert <%= flash_translation(key) %> fade in">
									<a href="#" data-dismiss="alert" class="close">×</a>
									<%= msg %>
								</div>
							<% end %>


							<% if content_for?(:title) %>
								<div class="page-header">
								  <div class="block">
			              <h1>
										  <%= yield(:title) %>
									  </h1>
									</div>
								</div>
							<% end %>

	            <%= yield %>
	          </div><!--/span-->
		      </div><!--/row-->
		    </div><!--/content-->
		   </div> <!-- /container -->
		</div><!--/wrapper-->

    <div class="push"><!--//--></div>

    <footer class="clear">
			<div id="left">&copy; 2012</div>
		  <div id="middle">
				&nbsp;
			</div>
			<div id="right" class="clear">
				<ul>
					<li id="js_link_text">
						<%= t(".js_link_text") %>:
					</li>
					<li id="js_logo">
						<%= link_to(image_tag("jumpstart-logo.png"), "http://www.jumpstart.ge", :target => "_blank",
								:title => t(".js_link_title")	) %>
					</li>
				</ul>
			</div>
    </footer>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
		<script type="text/javascript">
			I18n.defaultLocale = "<%= I18n.default_locale %>";
			I18n.locale = "<%= I18n.locale %>";
		</script>

		<% if Rails.env.production? %>
			<!-- insert google analytics for production site here -->
		<% elsif Rails.env.staging? %>
			<!-- insert google analytics for staging site here -->
		<% end %>

  </body>
</html>

app/views/layouts/application_root.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%
      desc = t('.about_text1')
      desc << " "
      desc << t('.about_text2')
    %>

    <meta name="description" content="<%= desc %>">

	  <meta property="og:title" content="<%= content_for?(:title) ? "#{yield(:title)} | #{t('app.common.app_name')}" :
			  t('app.common.app_name') %>" />
		<meta property="og:description" content="<%= desc %>" />
	  <meta property="og:type" content="non_profit" />
	  <meta property="og:url" content="<%= current_url %>" />
	  <meta property="og:image" content="<%= full_url(image_path('fb.jpg')) %>" />
	  <meta property="og:site_name" content="<%= t('app.common.app_name') %>" />

    <title><%= content_for?(:title) ? "#{yield(:title)} | #{t('app.common.app_name')}" :
				t('app.common.app_name') %></title>
    <%= csrf_meta_tags %>
	  <%= include_gon %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "fonts_#{I18n.locale}", :media => "all" %>
		<!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
	  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/favicon.ico?v=2', :rel => 'shortcut icon' %>
  </head>
  <body class="app_root">


    <div id="fb-root"></div>


    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container-fluid">

            <div class="row-fluid">
              <div class="span6 offset3" id="center_header">
                <% title_parts = t('app.common.app_name').reverse.split(' ', 2).map{ |x| x.reverse; }.reverse; %>
                <a href="<%= root_path(:locale => I18n.locale) %>">
                  <span><%= title_parts[0] %></span>
                  <span><%= title_parts[1] %></span>
                </a>
              </div>
              <div class="span3">
	              <ul class="nav pull-right nav-collapse">
		              <% if user_signed_in? %>
				            <li class="dropdown">
				              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
				                    <%= current_user.nickname %>
				                    <b class="caret"></b>
				              </a>
				              <ul class="dropdown-menu">
                   			<li>
                         <%= link_to t('.soldiers'), admin_soldiers_path %>
                        </li>
                        <% if current_user.role? User::ROLES[:admin] %>
                     			<li>
                           <%= link_to t('.users'), admin_users_path %>
                          </li>
                        <% end %> 		
						            <li>
				     		         <%= link_to t('.sign_out'), destroy_user_session_path, :method => :delete %>
										    </li>
				              </ul>
				            </li>
		              <% end %>
							    <% I18n.available_locales.each do |locale| %>
								    <% if locale != I18n.locale %>
									    <li class="locale_switcher"><%= link_to t("app.language.#{locale}"), params.merge(:locale => locale) %></li>
								    <% end %>
							    <% end %>
							    
                  <li id="social_fb">
				            <%= link_to(image_tag("share_fb.png"),
							            "http://www.facebook.com/share.php?u=#{root_url}", :title => "facebook",	:target => "_blank") %>
							    </li>
                  <li id="social_twitter">
				            <%= link_to(image_tag("share_tw.png"),
							            "https://twitter.com/share?url=#{root_url}", :title => "twitter", :target => "_blank") %>
							    </li>
                  <li id="social_share">
				            <%= link_to(image_tag("share_shr.png"), "#") %>
                    <div class="social_hover">
                      <div class="addthis_toolbox addthis_default_style ">
                        <a class="addthis_counter addthis_pill_style"></a>
                      </div>
                    </div>
							    </li>
	              </ul>
              </div>
            </div>

          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>



    <div id="header_bg">
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span4">
            <h1><%= @total_dead %></h1>
            <h3><%= t('.header2') %></h3>
          </div>
        </div>
      </div>
    </div>


    <div id="about_container">
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="inner span12">
            <!--h1><%= t('.about_header') %></h1-->
            <div><%= t('.about_text1') %></div>
            <div><%= t('.about_text2') %></div>
          </div>
        </div>
      </div>
    </div>

    <%= yield %>


    <footer class="clear">
			<div id="left">
        <div id="fb_likebox">
          <iframe id="fb_iframe" src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fferadi.info&amp;width=220&amp;height=70&amp;show_faces=false&amp;colorscheme=light&amp;stream=false&amp;show_border=false&amp;header=false&amp;" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:220px; height:70px;" allowTransparency="true"></iframe>
        </div>
      </div>
		  <div id="middle">
        <%= link_to t('.download'), root_path(:format => 'csv') %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<%= t('.last_updated', :date => @last_update) %>
			</div>
			<div id="right" class="clear">
				<ul>
					<li id="js_link_text">
						<%= t("layouts.application.js_link_text") %>:
					</li>
					<li id="js_logo">
						<%= link_to(image_tag("jumpstart-logo.png"), "http://www.jumpstart.ge", :target => "_blank",
								:title => t("layouts.application.js_link_title")	) %>
					</li>
				</ul>
			</div>
    </footer>



    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
		<script type="text/javascript">
			I18n.defaultLocale = "<%= I18n.default_locale %>";
			I18n.locale = "<%= I18n.locale %>";
      var locale = I18n.locale;
		</script>

    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=494884390560290";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    <script type="text/javascript">var addthis_config = {"data_track_addressbar":false};</script>
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-51d1537d4a09d85f"></script>

		<% if Rails.env.production? %>
			<!-- insert google analytics for production site here -->
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-12801815-25', 'jumpstart.ge');
        ga('send', 'pageview');

      </script>
 		<% elsif Rails.env.staging? %>
			<!-- insert google analytics for staging site here -->
		<% end %>

  </body>
</html>

app/views/layouts/unsupported_browser.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? "#{yield(:title)} | #{t('app.common.app_name')}" :
				t('app.common.app_name') %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
    <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to(t('app.common.app_name'), root_path(:locale => I18n.locale),:class=>"brand")%>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
  						<% I18n.available_locales.each do |locale| %>
  							<% if locale != I18n.locale %>
  								<li><%= link_to t("app.language.#{locale}"), params.merge(:locale => locale) %></li>
  							<% end %>
  						<% end %>
            </ul>
	        </div>
        </div>
      </div>
    </div>

		<div id="wrapper">
		  <div class="container">
		    <div class="content">
		      <div class="row">
		       <div class="span12">

		          <div class="page-header">
		            <h1>
									<%= t('.title') %>
								</h1>
							</div>

								<p><%= t('.p1') %></p>
								<p><%= t('.p2') %></p>
								<ul class="standard">
									<li>
										<a href="http://www.google.com/chrome/"><%= t('.chrome') %></a>
									</li>
									<li>
										<a href="http://www.mozilla.org/firefox/new/"><%= t('.firefox') %></a>
									</li>
									<li>
										<a href="http://windows.microsoft.com/en-US/internet-explorer/downloads/ie/"><%= t('.ie') %></a>
									</li>
									<li>
										<a href="http://www.opera.com/download/"><%= t('.opera') %></a>
									</li>
									<li>
										<a href="http://support.apple.com/downloads/#internet"><%= t('.safari') %></a>
									</li>
								</ul>
		        </div>
		      </div><!--/row-->
		    </div><!--/content-->
		  </div> <!-- /container -->
      <div class="push"><!--//--></div>
    </div><!--/wrapper-->


	<% if Rails.env.production? %>
		<!-- google analytics -->
	<% elsif Rails.env.staging? %>
		<!-- google analytics -->
	<% end %>

  </body>
</html>